# pragma once

# include <string>
# include <iomanip>
# include <iostream>
# include <vector>
# include <algorithm>
# include <functional>
# include <iterator>
# include <vector>
# include <iostream>
# include <map>
# include <exception>
# include <iostream>
# include <vector>
# include <algorithm>
# include <unistd.h>
# include <limits.h>
# include <iterator>
# include <limits.h>
# include <pthread.h>
# include <array>
# include <stdio.h>
# include <stdlib.h>
# include <string.h>
# include <math.h>
# include <ctype.h>
# include <time.h>
# include <unistd.h>
# include <deque>
# include <iostream>
# include <string>
# include <vector>
# include <iterator>

using namespace std;